FROM python:3.9-slim

RUN adduser --disabled-password --gecos '' user
COPY ./requirements*.txt /home/user/
RUN apt-get update && apt-get install -y postgresql openssl gcc libpq-dev
RUN pip install pip==24.0

RUN pip install --no-cache-dir -r /home/user/requirements-development.txt


COPY . /home/user/backend

EXPOSE 8000
USER user
WORKDIR /home/user/backend
ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=True

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]

